ProjetoEmebs2/ProjetoEmeb2/Controllers/ChamadoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ProjetoEmeb2.Models;

namespace ProjetoEmeb2.Controllers
{
    public class ChamadoController : Controller
    {
        [HttpGet]
        [HttpPost]
        public IActionResult Index(ChamadoModel formulario)
        {
            ViewBag.ListaPesquisa = formulario.ListaPesquisa();
            ViewBag.ListaChamado = formulario.ListaChamado();
            ViewBag.ListaEscola = new EscolaModel().ListaEscola();
            return View();
        }

        [HttpPost]
        public IActionResult CriarChamado(ChamadoModel formulario)
        {
            if (ModelState.IsValid)
            {
                formulario.Insert();
                return RedirectToAction("Index");
            }
            return View();

        }

        [HttpGet]
        public IActionResult CriarChamado(int? id)
        {
            if (id != null)
            {
                ChamadoModel objChamado = new ChamadoModel();
                ViewBag.Registro = objChamado.CarregarRegistro(id);

            }
            ViewBag.ListaEscola = new EscolaModel().ListaEscola();
            return View();
        }

        [HttpGet]
        public IActionResult ExcluirChamado(int id)
        {
            ChamadoModel objChamado = new ChamadoModel();
            objChamado.Excluir(id);
            return RedirectToAction("Index");
        }

        

    }
}

ProjetoEmebs2/ProjetoEmeb2/Controllers/ContaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ProjetoEmeb2.Models;

namespace ProjetoEmeb2.Controllers
{
    public class ContaController : Controller
    {
        public IActionResult Index()
        {
            ContaModel objConta = new ContaModel();
            ViewBag.ListaConta = objConta.ListaConta();
            return View();
        }

        
        [HttpPost]
        public IActionResult CriarConta(ContaModel formulario)
        {
            if (ModelState.IsValid)
            {
                formulario.Insert();
                return RedirectToAction("Index");
            }
            return View();

        }

        [HttpGet]
        public IActionResult CriarConta(int? id)
        {
            if (id != null)
            {
                ContaModel objConta = new ContaModel();
                ViewBag.Registro = objConta.CarregarRegistro(id);

            }
            ViewBag.ListaEscola = new EscolaModel().ListaEscola();

            return View();
        }

        [HttpGet]
        public IActionResult ExcluirConta(int id)
        {
            ContaModel objConta = new ContaModel();
            objConta.Excluir(id);
            return RedirectToAction("Index");
        }



    }
}

ProjetoEmebs2/ProjetoEmeb2/Controllers/EscolaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ProjetoEmeb2.Models;

namespace ProjetoEmeb2.Controllers
{
    public class EscolaController : Controller
    {
        /*IHttpContextAccessor HttpContextAccessor;
        public EscolaController(IHttpContextAccessor httpContextAccessor)
        {
            HttpContextAccessor = httpContextAccessor;
        }*/
        public IActionResult Index()
        {
            EscolaModel objEscola = new EscolaModel();
            ViewBag.ListaEscola = objEscola.ListaEscola();

            return View();
        }

        [HttpPost]
        public IActionResult CriarEscola(EscolaModel formulario)
        {
            if (ModelState.IsValid)
            {
                //formulario.HttpContextAccessor = httpContextAccessor;
                formulario.CadastrarEscola();
                return RedirectToAction("Index");
            }
            return View();
        }

       

        [HttpGet]
        public IActionResult CriarEscola(int? id)
        {
            if (id != null)
            {
                EscolaModel objEscola = new EscolaModel();
                ViewBag.Registro = objEscola.CarregarRegistro(id);

            }
            
            return View();
        }

        [HttpGet]
        public IActionResult ExcluirEscola(int id)
        {
            EscolaModel objEscola = new EscolaModel();
            objEscola.Excluir(id);
            return RedirectToAction("Index");
        }
  
        [HttpGet]
        public IActionResult Visualizar(int id)
        {
            EscolaModel objEscola = new EscolaModel();
            ViewBag.Registro = objEscola.CarregarRegistro(id);
            return View();

        }


    }
}

ProjetoEmebs2/ProjetoEmeb2/Controllers/FuncionarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ProjetoEmeb2.Models;

namespace ProjetoEmeb2.Controllers
{
    public class FuncionarioController : Controller
    {
        /*IHttpContextAccessor HttpContextAccessor;
        public EscolaController(IHttpContextAccessor httpContextAccessor)
        {
            HttpContextAccessor = httpContextAccessor;
        }*/
        public IActionResult Index()
        {
            FuncionarioModel objFuncionario = new FuncionarioModel();
            ViewBag.ListaFuncionario = objFuncionario.ListaFuncionario();

            return View();
        }

        [HttpPost]
        public IActionResult CriarFuncionario(FuncionarioModel formulario)
        {
            if (ModelState.IsValid)
            {

                formulario.CriarFuncionario();
                return RedirectToAction("Index");

            }
            return View();

        }



        [HttpGet]
        public IActionResult CriarFuncionario(int? id)
        {
            if (id != null)
            {
                FuncionarioModel objFuncionario = new FuncionarioModel();
                ViewBag.Registro = objFuncionario.CarregarRegistro(id);

            }

            return View();
        }

        [HttpGet]
        public IActionResult ExcluirFuncionario(int id)
        {
            FuncionarioModel objFuncionario = new FuncionarioModel();
            objFuncionario.Excluir(id);
            return RedirectToAction("Index");
        }


    }
}

ProjetoEmebs2/ProjetoEmeb2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Secretaria da Educação</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body onload="CarregarUsuarioLogado()">
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Secretaria da Educação</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Menu">Home</a></li>
                    <!-- <li><a asp-area="" asp-controller="Home" asp-action="About">Sobre</a></li>-->
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contato</a></li>
                    <li><a asp-area="" asp-controller="Escola" asp-action="Index">Escola</a></li>
                    <li><a asp-area="" asp-controller="Conta" asp-action="Index">Conta</a></li>
                    <li><a asp-area="" asp-controller="Chamado" asp-action="Index">Chamado</a></li>
                    <li><a asp-area="" asp-controller="Funcionario" asp-action="Index">Funcionario</a></li>

                </ul>
                @using Microsoft.AspNetCore.Http;
                @inject IHttpContextAccessor HttpContextAccessor

                <div id="NomeUsuarioLogado">
                </div>
                
            </div>
        </div>
    </nav>
    <div class="container body-content" style="padding-top:50px">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - ProjetoEmeb2</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)

    <script>
        function CarregarUsuarioLogado() {
            var nome = '@HttpContextAccessor.HttpContext.Session.GetString("NomeUsuarioLogado")'
            if (nome != "") {
                var divNome = document.getElementById("NomeUsuarioLogado");
                divNome.innerHTML = "Olá " + nome + "<a href='../Usuario/Login/0'>(Sair)</a>"
                divNome.style = "color:#fff; text-align:right; height:55px; padding-top:13px;"
            }
            else {
                window.location.href = '../Usuario/Login/';

            }
        }
    </script>
</body>
   


</html>

ProjetoEmebs2/ProjetoEmeb2/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Secretaria da Educação</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>

    <style>
        body{
            background-image: url('../../images/bg.jpg');
            background-repeat:no-repeat;
        }
    </style>

</head>
<body>
    <div class="container body-content" style="padding-top:160px">
        @RenderBody() 
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)

   
</body>
   


</html>